// <auto-generated />
using System;
using ConcurrentDbReadersExample.Tests.DatabaseAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ConcurrentDbReadersExample.Tests.DatabaseAccess.Migrations.Oracle
{
    [DbContext(typeof(OracleAppDbContext))]
    [Migration("20250609130835_SetUpOracle")]
    partial class SetUpOracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcurrentDbReadersExample.Tests.DatabaseAccess.OutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("JSON")
                        .HasColumnName("JSON_PAYLOAD");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PROCESSED_AT_UTC");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PROCESSED_BY");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id")
                        .HasName("PK_OUTBOX_ITEMS");

                    b.HasIndex("Id", "ProcessedAtUtc")
                        .HasDatabaseName("IX_OUTBOX_ITEMS_UNPROCESSED_ITEMS")
                        .HasFilter("PROCESSED_AT_UTC IS NULL");

                    b.ToTable("OUTBOX_ITEMS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
